version: '3.8'

services:
  mysqlsrv:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./volume_mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - "8181:8080"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
